
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fawdeexfzrfquhmxiaae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhd2RlZXhmenJmcXVobXhpYWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NzE3NzUsImV4cCI6MjA1NTI0Nzc3NX0.fHyf651EX8kUg67mKkVpBm7GmeUjZsyInyBAk7jKS4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
